Revision based on peer review feedback
brandmaier/research_software_evaluation pull request #26
Opened 2023-06-05 11:06 UTC by brandmaier

Response to comments from peer review.

2023-06-06 09:49 UTC, aaronpeikert requested changes

2023-06-06 09:49 UTC, aaronpeikert commented on manuscript.Rmd
> +Note that the requirements of a given academic position should guide the weighting of research software when evaluating and selecting candidates. In some cases, research software development may be c
Newline after sentence + comma

```suggestion
Note that the requirements of a given academic position should guide the weighting of research software when evaluating and selecting candidates.
In some cases, research software development may be central to a position and, therefore, a requirement (such as when hiring professors of statistics or research methods), but in other cases, we hope that research software development activities at least are considered as research output comparable to published papers.
```

2023-06-06 09:49 UTC, aaronpeikert commented on manuscript.Rmd
> +Therefore, we propose to penalize software if it does not adhere to an open-source license (those approved in a review process by the Open Source Initiative (https://opensource.org/licenses), for exa
Brackets do not line up.

```suggestion
Therefore, we propose to penalize software if it does not adhere to an open-source license (those approved in a review process by the [Open Source Initiative](https://opensource.org/licenses)), for example, by allowing them only half of the total achievable points.
```

2023-06-06 09:49 UTC, aaronpeikert commented on manuscript.Rmd
> +shorttitle        : "Rigor and impact"
```suggestion
shorttitle        : "Assessing research software"
```

2023-06-06 09:49 UTC, aaronpeikert commented on manuscript.Rmd
> +title             : "Assessing rigor and impact in research software"
```suggestion
title             : "Assessing rigor and impact of research software for hiring and promotion in psychology"
```

2023-06-06 10:38 UTC, aaronpeikert approved these changes

2023-06-07 11:42 UTC, Maximilian-Stefan-Ernst approved these changes

2023-06-07 11:42 UTC, Maximilian-Stefan-Ernst commented on manuscript.Rmd
> +title             : "Assessing rigor and impact of research software for hiring and promotion in psychology"
Finde ich super!

2023-06-07 12:49 UTC, aaronpeikert approved these changes

2023-06-07 19:00 UTC, merged